#!/usr/bin/env python3
"""Build the Texting With Cancer message feed from the source spreadsheet.

Reads `data/messages.csv` (the published Google Sheet, exported to CSV) and writes:

  * `js/messages.js`   -> `var TWC_MESSAGES = [ ... ];`  (what the site loads)
  * `js/messages.json` -> the same array as plain JSON (a portable data copy)

The site loads the data via a plain <script> tag (js/messages.js) rather than an
AJAX fetch, so it renders correctly straight from the filesystem (file://) with no
web server — and identically on GitHub Pages.

Every message is kept except rows whose COPY is empty. Image messages store their
photo inline in COPY as `<img src="img/NAME">`; this script reports any referenced
image that is not present in `img/` so we always know which originals are still
needed (a tasteful placeholder lives at that path until the original turns up).

Usage:
    python3 build.py
"""

import csv
import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(ROOT, "data", "messages.csv")
JS_PATH = os.path.join(ROOT, "js", "messages.js")
JSON_PATH = os.path.join(ROOT, "js", "messages.json")

# Matches the inline photo references in COPY, e.g. <img src="img/necklace.jpg">
IMG_RE = re.compile(r"""src=["']?(img/[^"'>\s]+)""")

FIELDS = ("DATE", "TIME", "AUTHOR", "COPY", "ASSETS")


def main():
    with open(CSV_PATH, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))

    messages = []
    skipped_empty = 0
    missing_images = {}

    for row in rows:
        copy = row.get("COPY") or ""
        if not copy.strip():
            skipped_empty += 1
            continue
        message = {
            "DATE": (row.get("DATE") or "").strip(),
            "TIME": (row.get("TIME") or "").strip(),
            "AUTHOR": (row.get("AUTHOR") or "").strip(),
            "COPY": copy,  # preserved verbatim (newlines + any inline <img> HTML)
            "ASSETS": (row.get("ASSETS") or "").strip(),
            "id": len(messages),
        }
        messages.append(message)
        for match in IMG_RE.finditer(copy):
            rel = match.group(1)
            if not os.path.exists(os.path.join(ROOT, rel)):
                missing_images[rel] = missing_images.get(rel, 0) + 1

    payload = json.dumps(messages, ensure_ascii=False)

    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        fh.write(payload)

    with open(JS_PATH, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by build.py from data/messages.csv -- do not edit by hand.\n")
        fh.write("var TWC_MESSAGES = " + payload + ";\n")

    print("messages written  : %d" % len(messages))
    print("empty rows skipped : %d" % skipped_empty)
    if messages:
        print("first COPY         : %r" % messages[0]["COPY"][:60])
        print("last  COPY         : %r" % messages[-1]["COPY"][:60])
    if missing_images:
        print("MISSING images (placeholder in use until the original is added):")
        for rel, count in sorted(missing_images.items()):
            print("   %s  (referenced %dx)" % (rel, count))
    else:
        print("all referenced images are present in img/.")


if __name__ == "__main__":
    main()
